version: '1.0'
name: CI_Action
displayName: CI_Action
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-677ecdc1
    displayName: CI流水线
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 构建Docker镜像
        type: cert
        certificate: 7c041d40-4db4-013d-e6e7-3e3dc62a28bf
        tag: go-blog:v1.${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./Dockerfile
        context: ''
        artifacts: []
        isCache: false
        parameter: {}
        notify: []
        strategy:
          retry: '0'
